In [1]:
import numpy as np
import pandas as pd

Create a numpy array

In [2]:
arr=np.array([[20,30,40,50,60],[1,2,6,4,5]])
print(arr)

[[20 30 40 50 60]
 [ 1  2  6  4  5]]


Create Two 1-D arrays each of 5 elements apply vector operations like addition and substraction

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])
print(a+b)
print(b-a)
print(a*b)
print(b/a)
print(np.dot(a,b))

[ 5  7  9 11 13]
[3 3 3 3 3]
[ 4 10 18 28 40]
[4.   2.5  2.   1.75 1.6 ]
100


In [4]:
np.zeros(dtype=int,shape=5)

array([0, 0, 0, 0, 0])

In [5]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

Create a 3-D array of shape (4,3,2) with all zero elements

In [6]:
np.zeros((4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [7]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Apply Logical Not Operation on an input array

Create an array 5,7,9 and create a shallow and deep copy of that array

In [9]:
a=np.array([5,7,9])
b=a.view()
b[0]=1
print(a)
print(b)

[1 7 9]
[1 7 9]


In [11]:
c=a.copy()
c[0]=5
print(a)
print(c)

[1 7 9]
[5 7 9]
